FROM mpeck/wip-ci-testing:latest

RUN apk update -U && \
    apk add bash make git ca-certificates openssl && \
    rm -f /var/cache/apk/*

RUN mix local.hex --force && \
    mix local.rebar --force

WORKDIR /code
COPY . /code
